export type HealthStatus = "Healthy" | "Degraded" | "Down";

export type ServiceDependency = {
  name: string;
  status: HealthStatus;
  latencyMs: number;
  errorRate: string;
  lastChecked: string;
  type: "Internal" | "External Provider" | "Infrastructure" | "Database";
};

export type ServiceIncident = {
  id: string;
  title: string;
  severity: "Critical" | "Major" | "Minor";
  status: "Investigating" | "Monitoring" | "Resolved";
  startedAt: string;
  duration?: string;
  affectedWorkspaces: number;
  rootCause: string;
};

export type RecentServiceIssue = {
  timestamp: string;
  statusCode?: number;
  title: string;
  detail: string;
  occurrences?: number;
  severity: "critical" | "warning" | "info";
  linkHref?: string;
};

export type HealthService = {
  id: string;
  name: string;
  product: string; // Sahayogi product name
  productSlug: string;
  serviceType: string;
  scope: string; // e.g. "WS-94812" or "NPCI Core" or "Multi-tenant"
  environment: "Production" | "Staging";
  responseTimeMs: number;
  errorRate: number; // e.g. 0.35 (%)
  sparkline: number[]; // 12 data points
  status: HealthStatus;
  primaryEndpoint: string;
  region: string;
  provider: string;
  providerSlug: string;
  version: string;
  description: string;
  slaTarget: number; // e.g. 99.9 (%)
  currentUptime: number; // e.g. 99.2 (%)
  lastDegradation: {
    timestamp: string;
    duration: string;
  };
  metrics: {
    p50Ms: number;
    p90Ms: number;
    p95Ms: number;
    p99Ms: number;
    requestVolumeRpm: number;
    peakReqSec: number;
    clientErrorRate: number; // 4xx
    serverErrorRate: number; // 5xx
    uptime24h: number;
    uptime7d: number;
    uptime30d: number;
    responseTrendData: Array<{ time: string; p95: number }>;
    errorTrendData: Array<{ time: string; rate: number }>;
  };
  dependencies: ServiceDependency[];
  incidents: ServiceIncident[];
  recentIssues: RecentServiceIssue[];
  configuration: {
    webhookEndpoint: string;
    provider: string;
    credentialMask: string;
    credentialStatus: string;
    environment: string;
    region: string;
    version: string;
    lastChanged: string;
    changedBy: string;
  };
  auditTrail: Array<{
    timestamp: string;
    actor: string;
    action: string;
    detail: string;
    result: "Success" | "Failed";
  }>;
};

export const MOCK_HEALTH_SERVICES: HealthService[] = [
  // 1. WhatsApp Gateway (Chat with Sahayogi) — Currently Selected Default (Degraded)
  {
    id: "svc-whatsapp-gateway",
    name: "WhatsApp Gateway",
    product: "Chat with Sahayogi",
    productSlug: "chat-with-sahayogi",
    serviceType: "Integration Gateway",
    scope: "WS-94812",
    environment: "Production",
    responseTimeMs: 840,
    errorRate: 0.35,
    sparkline: [280, 290, 310, 320, 305, 340, 680, 840, 810, 790, 830, 840],
    status: "Degraded",
    primaryEndpoint: "/v2/whatsapp/messages/webhook",
    region: "India (Mumbai)",
    provider: "Meta WhatsApp (WABA)",
    providerSlug: "meta-waba",
    version: "v2.8.1",
    description: "Handles WhatsApp message delivery, webhooks and media processing",
    slaTarget: 99.9,
    currentUptime: 99.2,
    lastDegradation: {
      timestamp: "28 Sep 2026, 14:12",
      duration: "18 mins",
    },
    metrics: {
      p50Ms: 120,
      p90Ms: 450,
      p95Ms: 840,
      p99Ms: 1420,
      requestVolumeRpm: 2410,
      peakReqSec: 48,
      clientErrorRate: 0.32,
      serverErrorRate: 0.03,
      uptime24h: 98.4,
      uptime7d: 99.1,
      uptime30d: 99.2,
      responseTrendData: [
        { time: "13:30", p95: 280 },
        { time: "13:40", p95: 310 },
        { time: "13:50", p95: 340 },
        { time: "14:00", p95: 840 },
        { time: "14:10", p95: 780 },
        { time: "14:20", p95: 840 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.01 },
        { time: "13:40", rate: 0.02 },
        { time: "13:50", rate: 0.04 },
        { time: "14:00", rate: 4.2 },
        { time: "14:10", rate: 0.8 },
        { time: "14:20", rate: 0.35 },
      ],
    },
    dependencies: [
      {
        name: "Meta WhatsApp Business Platform",
        status: "Degraded",
        latencyMs: 780,
        errorRate: "0.32%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
      {
        name: "Webhook Dispatch",
        status: "Healthy",
        latencyMs: 22,
        errorRate: "0.00%",
        lastChecked: "1 min ago",
        type: "Internal",
      },
      {
        name: "Message Queue",
        status: "Healthy",
        latencyMs: 8,
        errorRate: "0.00%",
        lastChecked: "1 min ago",
        type: "Infrastructure",
      },
      {
        name: "Media Processing",
        status: "Healthy",
        latencyMs: 45,
        errorRate: "0.01%",
        lastChecked: "2 mins ago",
        type: "Internal",
      },
      {
        name: "Credential Validation",
        status: "Degraded",
        latencyMs: 340,
        errorRate: "1.4%",
        lastChecked: "2 mins ago",
        type: "Internal",
      },
    ],
    incidents: [
      {
        id: "INC-10291",
        title: "WhatsApp webhook authentication failures",
        severity: "Major",
        status: "Investigating",
        startedAt: "28 Sep 2026, 14:12",
        affectedWorkspaces: 1,
        rootCause: "Provider token expiration & HMAC mismatch on WS-94812",
      },
      {
        id: "INC-10188",
        title: "Meta provider latency degradation",
        severity: "Minor",
        status: "Resolved",
        startedAt: "25 Sep 2026, 09:30",
        duration: "24 mins",
        affectedWorkspaces: 3,
        rootCause: "Upstream Meta Cloud API regional routing throttle",
      },
    ],
    recentIssues: [
      {
        timestamp: "14:24",
        statusCode: 401,
        title: "401 Unauthorized",
        detail: "HMAC signature mismatch on incoming webhook payload",
        occurrences: 7,
        severity: "critical",
        linkHref: "/technical-support/diagnostics?target=WS-94812",
      },
      {
        timestamp: "14:21",
        title: "Provider credential validation failed",
        detail: "Registered WABA OAuth token signature check failed",
        severity: "critical",
        linkHref: "/technical-support/diagnostics?target=WS-94812",
      },
      {
        timestamp: "14:12",
        title: "p95 latency exceeded SLA threshold",
        detail: "Latency peaked at 840 ms (SLA budget: 300 ms)",
        severity: "warning",
      },
      {
        timestamp: "13:58",
        title: "Webhook response timeout",
        detail: "Upstream egress timeout on batch delivery acknowledgment",
        severity: "warning",
      },
    ],
    configuration: {
      webhookEndpoint: "/v2/whatsapp/messages/webhook",
      provider: "Meta WhatsApp (WABA)",
      credentialMask: "meta_waba_prod_••••••92",
      credentialStatus: "Expired / Revalidation Required",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.8.1",
      lastChanged: "27 Sep 2026, 18:42",
      changedBy: "dhruv.singla@setu.co",
    },
    auditTrail: [
      {
        timestamp: "14:26",
        actor: "dhruv.singla@setu.co",
        action: "INTEGRATION_CREDENTIAL_REVALIDATED",
        detail: "Meta WABA Webhook Token (v2)",
        result: "Success",
      },
      {
        timestamp: "14:24",
        actor: "Diagnostic Execution",
        action: "HMAC_SIGNATURE_CHECK",
        detail: "Probe against WS-94812",
        result: "Failed",
      },
      {
        timestamp: "14:12",
        actor: "System Watchdog",
        action: "SERVICE_HEALTH_DEGRADED",
        detail: "WhatsApp Gateway latency & 401 spike",
        result: "Success",
      },
    ],
  },

  // 2. UPI Payment Switch (BoSS)
  {
    id: "svc-upi-switch",
    name: "UPI Payment Switch",
    product: "BoSS",
    productSlug: "boss",
    serviceType: "Payment Switch",
    scope: "NPCI Core",
    environment: "Production",
    responseTimeMs: 18,
    errorRate: 0.01,
    sparkline: [22, 20, 19, 18, 19, 17, 18, 18, 19, 18, 17, 18],
    status: "Healthy",
    primaryEndpoint: "/v3/upi/transaction/process",
    region: "India (Mumbai)",
    provider: "NPCI Core / Razorpay",
    providerSlug: "razorpay",
    version: "v4.1.0",
    description: "Real-time UPI transaction routing, dynamic QR parsing, and settlement bridge",
    slaTarget: 99.99,
    currentUptime: 99.99,
    lastDegradation: {
      timestamp: "12 Sep 2026, 03:15",
      duration: "4 mins",
    },
    metrics: {
      p50Ms: 14,
      p90Ms: 19,
      p95Ms: 24,
      p99Ms: 42,
      requestVolumeRpm: 18450,
      peakReqSec: 320,
      clientErrorRate: 0.01,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.99,
      uptime30d: 99.99,
      responseTrendData: [
        { time: "13:30", p95: 22 },
        { time: "13:40", p95: 19 },
        { time: "13:50", p95: 20 },
        { time: "14:00", p95: 24 },
        { time: "14:10", p95: 21 },
        { time: "14:20", p95: 18 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.01 },
        { time: "13:40", rate: 0.01 },
        { time: "13:50", rate: 0.0 },
        { time: "14:00", rate: 0.02 },
        { time: "14:10", rate: 0.01 },
        { time: "14:20", rate: 0.01 },
      ],
    },
    dependencies: [
      {
        name: "NPCI UPI Switching Network",
        status: "Healthy",
        latencyMs: 14,
        errorRate: "0.00%",
        lastChecked: "30s ago",
        type: "External Provider",
      },
      {
        name: "Razorpay Core Settlement Engine",
        status: "Healthy",
        latencyMs: 16,
        errorRate: "0.01%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
    ],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v3/upi/transaction/webhook",
      provider: "NPCI Core",
      credentialMask: "npci_switch_••••••48",
      credentialStatus: "Active & Validated",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v4.1.0",
      lastChanged: "20 Sep 2026, 11:20",
      changedBy: "ops.lead@setu.co",
    },
    auditTrail: [],
  },

  // 3. BBPS Bill Rail (BoSS)
  {
    id: "svc-bbps-rail",
    name: "BBPS Bill Rail",
    product: "BoSS",
    productSlug: "boss",
    serviceType: "Biller Network Bridge",
    scope: "Bharat BillPay",
    environment: "Production",
    responseTimeMs: 24,
    errorRate: 0.02,
    sparkline: [26, 25, 24, 25, 24, 23, 25, 24, 24, 23, 24, 24],
    status: "Healthy",
    primaryEndpoint: "/v2/bbps/bills/fetch",
    region: "India (Mumbai)",
    provider: "NPCI Bharat BillPay",
    providerSlug: "razorpay",
    version: "v3.2.4",
    description: "National biller fetch and payment clearance network bridge",
    slaTarget: 99.95,
    currentUptime: 99.98,
    lastDegradation: {
      timestamp: "18 Sep 2026, 08:40",
      duration: "6 mins",
    },
    metrics: {
      p50Ms: 18,
      p90Ms: 28,
      p95Ms: 36,
      p99Ms: 65,
      requestVolumeRpm: 8200,
      peakReqSec: 140,
      clientErrorRate: 0.02,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.98,
      uptime30d: 99.98,
      responseTrendData: [
        { time: "13:30", p95: 26 },
        { time: "13:40", p95: 25 },
        { time: "13:50", p95: 24 },
        { time: "14:00", p95: 27 },
        { time: "14:10", p95: 25 },
        { time: "14:20", p95: 24 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.02 },
        { time: "13:40", rate: 0.02 },
        { time: "13:50", rate: 0.01 },
        { time: "14:00", rate: 0.02 },
        { time: "14:10", rate: 0.02 },
        { time: "14:20", rate: 0.02 },
      ],
    },
    dependencies: [
      {
        name: "NPCI Central BBPS OU Switch",
        status: "Healthy",
        latencyMs: 22,
        errorRate: "0.01%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
    ],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v2/bbps/bills/payment",
      provider: "NPCI Bharat BillPay",
      credentialMask: "bbps_ou_••••••11",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v3.2.4",
      lastChanged: "15 Sep 2026, 14:10",
      changedBy: "ops.lead@setu.co",
    },
    auditTrail: [],
  },

  // 4. Tally on Cloud (Sahayogi Cloud)
  {
    id: "svc-tally-cloud",
    name: "Tally on Cloud",
    product: "Sahayogi Cloud",
    productSlug: "sahayogi-cloud",
    serviceType: "Cloud ERP Provisioner",
    scope: "WS-77211",
    environment: "Production",
    responseTimeMs: 320,
    errorRate: 0.05,
    sparkline: [310, 315, 320, 325, 318, 322, 320, 330, 325, 320, 318, 320],
    status: "Healthy",
    primaryEndpoint: "/v1/tally/company/sync",
    region: "India (Mumbai)",
    provider: "Tally on Cloud",
    providerSlug: "tally",
    version: "v5.0.2",
    description: "Virtual container control plane for multi-tenant Tally Prime & Busy accounting software",
    slaTarget: 99.9,
    currentUptime: 99.94,
    lastDegradation: {
      timestamp: "24 Sep 2026, 19:10",
      duration: "12 mins",
    },
    metrics: {
      p50Ms: 240,
      p90Ms: 340,
      p95Ms: 410,
      p99Ms: 780,
      requestVolumeRpm: 1200,
      peakReqSec: 25,
      clientErrorRate: 0.04,
      serverErrorRate: 0.01,
      uptime24h: 99.95,
      uptime7d: 99.92,
      uptime30d: 99.94,
      responseTrendData: [
        { time: "13:30", p95: 310 },
        { time: "13:40", p95: 320 },
        { time: "13:50", p95: 330 },
        { time: "14:00", p95: 350 },
        { time: "14:10", p95: 330 },
        { time: "14:20", p95: 320 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.04 },
        { time: "13:40", rate: 0.05 },
        { time: "13:50", rate: 0.05 },
        { time: "14:00", rate: 0.06 },
        { time: "14:10", rate: 0.05 },
        { time: "14:20", rate: 0.05 },
      ],
    },
    dependencies: [
      {
        name: "Tally Prime Container Daemon",
        status: "Healthy",
        latencyMs: 290,
        errorRate: "0.04%",
        lastChecked: "2 mins ago",
        type: "Infrastructure",
      },
    ],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/tally/company/sync",
      provider: "Tally on Cloud",
      credentialMask: "tally_vault_••••••99",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v5.0.2",
      lastChanged: "22 Sep 2026, 16:30",
      changedBy: "cloud.team@setu.co",
    },
    auditTrail: [],
  },

  // 5. GSTN Ingestion & E-Way (Tax Sahayogi)
  {
    id: "svc-gstn-ingestion",
    name: "GSTN Ingestion & E-Way",
    product: "Tax Sahayogi",
    productSlug: "tax-sahayogi",
    serviceType: "Compliance Bridge",
    scope: "NIC Portal",
    environment: "Production",
    responseTimeMs: 42,
    errorRate: 0.0,
    sparkline: [45, 43, 44, 42, 43, 41, 42, 44, 43, 42, 41, 42],
    status: "Healthy",
    primaryEndpoint: "/v2/gst/eway/generate",
    region: "India (Mumbai)",
    provider: "GSTN / NIC Portal",
    providerSlug: "nic-gst",
    version: "v2.4.0",
    description: "National Informatics Centre GST portal API integration for GSTR filing & E-Way clearance",
    slaTarget: 99.9,
    currentUptime: 99.98,
    lastDegradation: {
      timestamp: "15 Sep 2026, 12:00",
      duration: "10 mins",
    },
    metrics: {
      p50Ms: 32,
      p90Ms: 46,
      p95Ms: 58,
      p99Ms: 110,
      requestVolumeRpm: 4600,
      peakReqSec: 85,
      clientErrorRate: 0.0,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.98,
      uptime30d: 99.98,
      responseTrendData: [
        { time: "13:30", p95: 45 },
        { time: "13:40", p95: 44 },
        { time: "13:50", p95: 42 },
        { time: "14:00", p95: 46 },
        { time: "14:10", p95: 43 },
        { time: "14:20", p95: 42 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.0 },
        { time: "13:40", rate: 0.0 },
        { time: "13:50", rate: 0.0 },
        { time: "14:00", rate: 0.0 },
        { time: "14:10", rate: 0.0 },
        { time: "14:20", rate: 0.0 },
      ],
    },
    dependencies: [
      {
        name: "NIC Public GST Gateway",
        status: "Healthy",
        latencyMs: 38,
        errorRate: "0.00%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
    ],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v2/gst/eway/generate",
      provider: "NIC Portal",
      credentialMask: "nic_gst_••••••77",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.4.0",
      lastChanged: "10 Sep 2026, 10:15",
      changedBy: "tax.eng@setu.co",
    },
    auditTrail: [],
  },

  // 6. KYC & DigiLocker (Sahayogi One)
  {
    id: "svc-kyc-digilocker",
    name: "KYC & DigiLocker",
    product: "Sahayogi One",
    productSlug: "sahayogi-one",
    serviceType: "Identity Provider",
    scope: "UIDAI / NSDL",
    environment: "Production",
    responseTimeMs: 36,
    errorRate: 0.01,
    sparkline: [38, 37, 36, 35, 36, 37, 36, 38, 36, 35, 36, 36],
    status: "Healthy",
    primaryEndpoint: "/v1/kyc/aadhaar/otp-verify",
    region: "India (Mumbai)",
    provider: "UIDAI / NSDL",
    providerSlug: "setu-aa",
    version: "v3.1.2",
    description: "DigiLocker document exchange and Aadhaar OKYC verification rail",
    slaTarget: 99.95,
    currentUptime: 99.97,
    lastDegradation: {
      timestamp: "14 Sep 2026, 16:30",
      duration: "5 mins",
    },
    metrics: {
      p50Ms: 28,
      p90Ms: 42,
      p95Ms: 52,
      p99Ms: 95,
      requestVolumeRpm: 3100,
      peakReqSec: 60,
      clientErrorRate: 0.01,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.97,
      uptime30d: 99.97,
      responseTrendData: [
        { time: "13:30", p95: 38 },
        { time: "13:40", p95: 36 },
        { time: "13:50", p95: 37 },
        { time: "14:00", p95: 39 },
        { time: "14:10", p95: 37 },
        { time: "14:20", p95: 36 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.01 },
        { time: "13:40", rate: 0.01 },
        { time: "13:50", rate: 0.0 },
        { time: "14:00", rate: 0.01 },
        { time: "14:10", rate: 0.01 },
        { time: "14:20", rate: 0.01 },
      ],
    },
    dependencies: [
      {
        name: "UIDAI eKYC Gateway",
        status: "Healthy",
        latencyMs: 32,
        errorRate: "0.01%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
    ],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/kyc/aadhaar/otp-verify",
      provider: "UIDAI / NSDL",
      credentialMask: "uidai_auth_••••••33",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v3.1.2",
      lastChanged: "08 Sep 2026, 09:00",
      changedBy: "security@setu.co",
    },
    auditTrail: [],
  },

  // 7. FastTag NETC Transit (BoSS)
  {
    id: "svc-fasttag-transit",
    name: "FastTag NETC Transit",
    product: "BoSS",
    productSlug: "boss",
    serviceType: "Transit Clearance",
    scope: "NETC Switch",
    environment: "Production",
    responseTimeMs: 29,
    errorRate: 0.03,
    sparkline: [31, 30, 29, 32, 28, 29, 30, 29, 31, 29, 28, 29],
    status: "Healthy",
    primaryEndpoint: "/v1/netc/toll/recharge",
    region: "India (Mumbai)",
    provider: "NETC Switch",
    providerSlug: "razorpay",
    version: "v2.1.8",
    description: "National Electronic Toll Collection transit billing and vehicle RFID reconciliation",
    slaTarget: 99.9,
    currentUptime: 99.95,
    lastDegradation: {
      timestamp: "20 Sep 2026, 04:10",
      duration: "8 mins",
    },
    metrics: {
      p50Ms: 22,
      p90Ms: 34,
      p95Ms: 44,
      p99Ms: 80,
      requestVolumeRpm: 5400,
      peakReqSec: 90,
      clientErrorRate: 0.03,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.95,
      uptime30d: 99.95,
      responseTrendData: [
        { time: "13:30", p95: 31 },
        { time: "13:40", p95: 29 },
        { time: "13:50", p95: 30 },
        { time: "14:00", p95: 33 },
        { time: "14:10", p95: 30 },
        { time: "14:20", p95: 29 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.03 },
        { time: "13:40", rate: 0.03 },
        { time: "13:50", rate: 0.02 },
        { time: "14:00", rate: 0.03 },
        { time: "14:10", rate: 0.03 },
        { time: "14:20", rate: 0.03 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/netc/toll/recharge",
      provider: "NETC Switch",
      credentialMask: "netc_toll_••••••24",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.1.8",
      lastChanged: "12 Sep 2026, 13:40",
      changedBy: "ops.lead@setu.co",
    },
    auditTrail: [],
  },

  // 8. IMPS / Account Verify (BoSS)
  {
    id: "svc-imps-verify",
    name: "IMPS / Account Verify",
    product: "BoSS",
    productSlug: "boss",
    serviceType: "Penny Drop & Bank Verification",
    scope: "IMPS Switch",
    environment: "Production",
    responseTimeMs: 55,
    errorRate: 0.01,
    sparkline: [58, 56, 55, 57, 54, 55, 56, 55, 57, 56, 54, 55],
    status: "Healthy",
    primaryEndpoint: "/v1/banking/account/penny-drop",
    region: "India (Mumbai)",
    provider: "IMPS Switch",
    providerSlug: "razorpay",
    version: "v3.0.1",
    description: "Real-time bank account validation, beneficiary name resolution, and IFSC routing",
    slaTarget: 99.9,
    currentUptime: 99.96,
    lastDegradation: {
      timestamp: "11 Sep 2026, 02:45",
      duration: "6 mins",
    },
    metrics: {
      p50Ms: 44,
      p90Ms: 68,
      p95Ms: 82,
      p99Ms: 145,
      requestVolumeRpm: 6800,
      peakReqSec: 110,
      clientErrorRate: 0.01,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.96,
      uptime30d: 99.96,
      responseTrendData: [
        { time: "13:30", p95: 58 },
        { time: "13:40", p95: 55 },
        { time: "13:50", p95: 56 },
        { time: "14:00", p95: 60 },
        { time: "14:10", p95: 57 },
        { time: "14:20", p95: 55 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.01 },
        { time: "13:40", rate: 0.01 },
        { time: "13:50", rate: 0.01 },
        { time: "14:00", rate: 0.02 },
        { time: "14:10", rate: 0.01 },
        { time: "14:20", rate: 0.01 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/banking/account/penny-drop",
      provider: "IMPS Switch",
      credentialMask: "imps_route_••••••55",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v3.0.1",
      lastChanged: "14 Sep 2026, 17:00",
      changedBy: "ops.lead@setu.co",
    },
    auditTrail: [],
  },

  // 9. SMS & OTP Gateway (Chat with Sahayogi) — Degraded
  {
    id: "svc-sms-gateway",
    name: "SMS & OTP Gateway",
    product: "Chat with Sahayogi",
    productSlug: "chat-with-sahayogi",
    serviceType: "Telecom Delivery Bridge",
    scope: "SMS Provider",
    environment: "Production",
    responseTimeMs: 320,
    errorRate: 2.1,
    sparkline: [180, 190, 210, 230, 250, 270, 310, 340, 330, 325, 315, 320],
    status: "Degraded",
    primaryEndpoint: "/v1/messaging/sms/dispatch",
    region: "India (Mumbai)",
    provider: "Telco Route A / DLT",
    providerSlug: "meta-waba",
    version: "v2.1.0",
    description: "Two-factor authentication OTP delivery and transaction notification telecom gateway",
    slaTarget: 99.9,
    currentUptime: 98.7,
    lastDegradation: {
      timestamp: "28 Sep 2026, 13:55",
      duration: "35 mins",
    },
    metrics: {
      p50Ms: 240,
      p90Ms: 380,
      p95Ms: 490,
      p99Ms: 920,
      requestVolumeRpm: 4200,
      peakReqSec: 80,
      clientErrorRate: 0.4,
      serverErrorRate: 1.7,
      uptime24h: 98.7,
      uptime7d: 99.0,
      uptime30d: 98.9,
      responseTrendData: [
        { time: "13:30", p95: 180 },
        { time: "13:40", p95: 210 },
        { time: "13:50", p95: 280 },
        { time: "14:00", p95: 350 },
        { time: "14:10", p95: 330 },
        { time: "14:20", p95: 320 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.2 },
        { time: "13:40", rate: 0.5 },
        { time: "13:50", rate: 1.8 },
        { time: "14:00", rate: 2.4 },
        { time: "14:10", rate: 2.2 },
        { time: "14:20", rate: 2.1 },
      ],
    },
    dependencies: [
      {
        name: "Primary Telecom Aggregator",
        status: "Degraded",
        latencyMs: 310,
        errorRate: "2.1%",
        lastChecked: "1 min ago",
        type: "External Provider",
      },
    ],
    incidents: [
      {
        id: "INC-10290",
        title: "Telecom aggregator DLT queue delay",
        severity: "Major",
        status: "Monitoring",
        startedAt: "28 Sep 2026, 13:55",
        affectedWorkspaces: 8,
        rootCause: "Carrier traffic congestion on Jio/Airtel interconnect link",
      },
    ],
    recentIssues: [
      {
        timestamp: "14:15",
        title: "DLT delivery report latency spike",
        detail: "OTP delivery SLA dropped below 95% within 15 seconds",
        severity: "warning",
      },
    ],
    configuration: {
      webhookEndpoint: "/v1/messaging/sms/dispatch",
      provider: "Telco Route A",
      credentialMask: "telco_dlt_••••••88",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.1.0",
      lastChanged: "19 Sep 2026, 10:00",
      changedBy: "comms.team@setu.co",
    },
    auditTrail: [],
  },

  // 10. Investor Market Data (Investor Sahayogi) — Down / Major Dependency Outage
  {
    id: "svc-market-data",
    name: "Market Data Feed",
    product: "Investor Sahayogi",
    productSlug: "investor-sahayogi",
    serviceType: "RTA Financial Stream",
    scope: "CAMS / KFintech",
    environment: "Production",
    responseTimeMs: 2400,
    errorRate: 14.8,
    sparkline: [210, 240, 290, 480, 890, 1400, 2100, 2400, 2400, 2400, 2400, 2400],
    status: "Down",
    primaryEndpoint: "/v1/investor/portfolio/nav-sync",
    region: "India (Mumbai)",
    provider: "CAMS / KFintech Statement Feed",
    providerSlug: "cams",
    version: "v1.9.4",
    description: "Daily NAV synchronization, portfolio statement feeds, and mutual fund valuation",
    slaTarget: 99.8,
    currentUptime: 96.4,
    lastDegradation: {
      timestamp: "28 Sep 2026, 13:30",
      duration: "55 mins",
    },
    metrics: {
      p50Ms: 1200,
      p90Ms: 2100,
      p95Ms: 2400,
      p99Ms: 4100,
      requestVolumeRpm: 840,
      peakReqSec: 15,
      clientErrorRate: 2.1,
      serverErrorRate: 12.7,
      uptime24h: 96.4,
      uptime7d: 98.2,
      uptime30d: 98.5,
      responseTrendData: [
        { time: "13:30", p95: 210 },
        { time: "13:40", p95: 480 },
        { time: "13:50", p95: 1400 },
        { time: "14:00", p95: 2400 },
        { time: "14:10", p95: 2400 },
        { time: "14:20", p95: 2400 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.1 },
        { time: "13:40", rate: 1.2 },
        { time: "13:50", rate: 8.4 },
        { time: "14:00", rate: 14.8 },
        { time: "14:10", rate: 14.8 },
        { time: "14:20", rate: 14.8 },
      ],
    },
    dependencies: [
      {
        name: "CAMS Upstream Financial Bridge",
        status: "Down",
        latencyMs: 2400,
        errorRate: "14.8%",
        lastChecked: "30s ago",
        type: "External Provider",
      },
    ],
    incidents: [
      {
        id: "INC-10288",
        title: "CAMS mutual fund feed rate-limit & upstream outage",
        severity: "Critical",
        status: "Investigating",
        startedAt: "28 Sep 2026, 13:30",
        affectedWorkspaces: 12,
        rootCause: "Upstream RTA quota exhausted during afternoon market reconciliation",
      },
    ],
    recentIssues: [
      {
        timestamp: "14:09",
        statusCode: 429,
        title: "429 Rate Limited",
        detail: "Aggregator rate limit exceeded (120 calls/min quota reached)",
        occurrences: 18,
        severity: "critical",
      },
    ],
    configuration: {
      webhookEndpoint: "/v1/investor/portfolio/nav-sync",
      provider: "CAMS / KFintech",
      credentialMask: "cams_rta_••••••61",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v1.9.4",
      lastChanged: "18 Sep 2026, 11:30",
      changedBy: "investor.eng@setu.co",
    },
    auditTrail: [],
  },

  // 11. Payslip Dispatch Service (My Sahayogi)
  {
    id: "svc-payslip-dispatch",
    name: "Payslip Dispatch Service",
    product: "My Sahayogi",
    productSlug: "my-sahayogi",
    serviceType: "Financial Records Engine",
    scope: "Setu AA",
    environment: "Production",
    responseTimeMs: 64,
    errorRate: 0.0,
    sparkline: [68, 65, 66, 64, 63, 65, 64, 66, 64, 63, 64, 64],
    status: "Healthy",
    primaryEndpoint: "/v1/my/payroll/dispatch",
    region: "India (Mumbai)",
    provider: "Setu Account Aggregator",
    providerSlug: "setu-aa",
    version: "v2.3.0",
    description: "Employee digital payslip encryption, verification, and automated dispatch pipeline",
    slaTarget: 99.9,
    currentUptime: 99.98,
    lastDegradation: {
      timestamp: "05 Sep 2026, 01:20",
      duration: "4 mins",
    },
    metrics: {
      p50Ms: 48,
      p90Ms: 78,
      p95Ms: 95,
      p99Ms: 160,
      requestVolumeRpm: 1800,
      peakReqSec: 35,
      clientErrorRate: 0.0,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.98,
      uptime30d: 99.98,
      responseTrendData: [
        { time: "13:30", p95: 68 },
        { time: "13:40", p95: 66 },
        { time: "13:50", p95: 64 },
        { time: "14:00", p95: 67 },
        { time: "14:10", p95: 65 },
        { time: "14:20", p95: 64 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.0 },
        { time: "13:40", rate: 0.0 },
        { time: "13:50", rate: 0.0 },
        { time: "14:00", rate: 0.0 },
        { time: "14:10", rate: 0.0 },
        { time: "14:20", rate: 0.0 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/my/payroll/dispatch",
      provider: "Setu AA",
      credentialMask: "aa_vault_••••••40",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.3.0",
      lastChanged: "01 Sep 2026, 12:00",
      changedBy: "my.eng@setu.co",
    },
    auditTrail: [],
  },

  // 12. AI Diffusion & Asset Service (Studio Sahayogi)
  {
    id: "svc-studio-diffusion",
    name: "AI Diffusion & Asset Service",
    product: "Studio Sahayogi",
    productSlug: "studio-sahayogi",
    serviceType: "GPU Inference Cluster",
    scope: "Midjourney GPU",
    environment: "Production",
    responseTimeMs: 1020,
    errorRate: 0.02,
    sparkline: [980, 1010, 1050, 1030, 1015, 1020, 1040, 1030, 1020, 1010, 1025, 1020],
    status: "Healthy",
    primaryEndpoint: "/v2/studio/assets/generate",
    region: "India (Mumbai)",
    provider: "GPU Cluster / Midjourney",
    providerSlug: "midjourney",
    version: "v3.0.0",
    description: "Generative creative assets, marketing banner rendering, and image diffusion workflow",
    slaTarget: 99.5,
    currentUptime: 99.85,
    lastDegradation: {
      timestamp: "19 Sep 2026, 21:00",
      duration: "14 mins",
    },
    metrics: {
      p50Ms: 820,
      p90Ms: 1180,
      p95Ms: 1420,
      p99Ms: 2400,
      requestVolumeRpm: 620,
      peakReqSec: 12,
      clientErrorRate: 0.02,
      serverErrorRate: 0.0,
      uptime24h: 99.9,
      uptime7d: 99.85,
      uptime30d: 99.85,
      responseTrendData: [
        { time: "13:30", p95: 980 },
        { time: "13:40", p95: 1010 },
        { time: "13:50", p95: 1050 },
        { time: "14:00", p95: 1030 },
        { time: "14:10", p95: 1020 },
        { time: "14:20", p95: 1020 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.02 },
        { time: "13:40", rate: 0.02 },
        { time: "13:50", rate: 0.02 },
        { time: "14:00", rate: 0.02 },
        { time: "14:10", rate: 0.02 },
        { time: "14:20", rate: 0.02 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v2/studio/assets/generate",
      provider: "GPU Cluster",
      credentialMask: "gpu_orch_••••••52",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v3.0.0",
      lastChanged: "15 Sep 2026, 18:00",
      changedBy: "studio.lead@setu.co",
    },
    auditTrail: [],
  },

  // 13. Deep Link Service (Office Sahayogi)
  {
    id: "svc-deep-link",
    name: "Deep Link Service",
    product: "Office Sahayogi",
    productSlug: "office-sahayogi",
    serviceType: "Workflow Resolution",
    scope: "Microsoft 365",
    environment: "Production",
    responseTimeMs: 48,
    errorRate: 0.0,
    sparkline: [52, 50, 48, 49, 47, 48, 49, 48, 47, 48, 49, 48],
    status: "Healthy",
    primaryEndpoint: "/v1/office/deeplink/resolve",
    region: "India (Mumbai)",
    provider: "Microsoft Graph / 365 API",
    providerSlug: "microsoft-365",
    version: "v2.0.4",
    description: "Cross-tenant document link routing and Microsoft 365 authenticated collaboration resolver",
    slaTarget: 99.95,
    currentUptime: 99.99,
    lastDegradation: {
      timestamp: "02 Sep 2026, 05:00",
      duration: "3 mins",
    },
    metrics: {
      p50Ms: 38,
      p90Ms: 56,
      p95Ms: 70,
      p99Ms: 120,
      requestVolumeRpm: 7200,
      peakReqSec: 130,
      clientErrorRate: 0.0,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.99,
      uptime30d: 99.99,
      responseTrendData: [
        { time: "13:30", p95: 52 },
        { time: "13:40", p95: 50 },
        { time: "13:50", p95: 48 },
        { time: "14:00", p95: 51 },
        { time: "14:10", p95: 49 },
        { time: "14:20", p95: 48 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.0 },
        { time: "13:40", rate: 0.0 },
        { time: "13:50", rate: 0.0 },
        { time: "14:00", rate: 0.0 },
        { time: "14:10", rate: 0.0 },
        { time: "14:20", rate: 0.0 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/office/deeplink/resolve",
      provider: "Microsoft Graph API",
      credentialMask: "msft_graph_••••••19",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v2.0.4",
      lastChanged: "04 Sep 2026, 15:20",
      changedBy: "office.eng@setu.co",
    },
    auditTrail: [],
  },

  // 14. Sahayogi AI Shared Intelligence Gateway (Shared Platform Layer)
  {
    id: "svc-sahayogi-ai-gateway",
    name: "Sahayogi AI Gateway",
    product: "Sahayogi AI (Shared Layer)",
    productSlug: "chat-with-sahayogi", // Shared fallback
    serviceType: "Shared Intelligence Layer",
    scope: "Platform-wide",
    environment: "Production",
    responseTimeMs: 380,
    errorRate: 0.01,
    sparkline: [360, 370, 390, 385, 380, 375, 385, 380, 385, 378, 382, 380],
    status: "Healthy",
    primaryEndpoint: "/v1/ai/copilot/inference",
    region: "India (Mumbai)",
    provider: "Google Gemini 2.5 Flash Cluster",
    providerSlug: "meta-waba",
    version: "v3.2.0",
    description: "Shared LLM copilot, intent classification, and document intelligence layer across Sahayogi apps",
    slaTarget: 99.9,
    currentUptime: 99.96,
    lastDegradation: {
      timestamp: "16 Sep 2026, 04:30",
      duration: "8 mins",
    },
    metrics: {
      p50Ms: 290,
      p90Ms: 440,
      p95Ms: 580,
      p99Ms: 1100,
      requestVolumeRpm: 5800,
      peakReqSec: 95,
      clientErrorRate: 0.01,
      serverErrorRate: 0.0,
      uptime24h: 100,
      uptime7d: 99.96,
      uptime30d: 99.96,
      responseTrendData: [
        { time: "13:30", p95: 360 },
        { time: "13:40", p95: 370 },
        { time: "13:50", p95: 390 },
        { time: "14:00", p95: 410 },
        { time: "14:10", p95: 390 },
        { time: "14:20", p95: 380 },
      ],
      errorTrendData: [
        { time: "13:30", rate: 0.01 },
        { time: "13:40", rate: 0.01 },
        { time: "13:50", rate: 0.01 },
        { time: "14:00", rate: 0.02 },
        { time: "14:10", rate: 0.01 },
        { time: "14:20", rate: 0.01 },
      ],
    },
    dependencies: [],
    incidents: [],
    recentIssues: [],
    configuration: {
      webhookEndpoint: "/v1/ai/copilot/inference",
      provider: "Google Gemini Vertex Cluster",
      credentialMask: "gemini_vertex_••••••88",
      credentialStatus: "Active",
      environment: "Production",
      region: "India (Mumbai)",
      version: "v3.2.0",
      lastChanged: "20 Sep 2026, 14:00",
      changedBy: "ai.team@setu.co",
    },
    auditTrail: [],
  },
];
