export type IntegrationStatus = "Healthy" | "Degraded" | "Attention" | "Down";

export interface IntegrationEndpoint {
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  status: IntegrationStatus;
  p95: number;
  errorRate: string;
  reqsPerMin: string;
}

export interface DependentService {
  name: string;
  status: IntegrationStatus;
  p95: number;
  errorRate: string;
  lastCheck: string;
  product: string;
}

export interface WorkspaceUsage {
  name: string;
  wsId: string;
  product: string;
  status: IntegrationStatus;
  txVolume: string;
  lastActive: string;
}

export interface IntegrationIssue {
  date: string;
  issue: string;
  severity: "Low" | "Medium" | "High" | "Critical";
  status: "Resolved" | "Investigating" | "Monitoring";
  affectedWorkspaces: number;
}

export interface SafeConfiguration {
  provider: string;
  environment: string;
  region: string;
  primaryEndpoint: string;
  backupEndpoint: string;
  maskedCredential: string;
  credentialStatus: string;
  lastValidation: string;
  tlsCipher: string;
  webhookEndpoint: string;
  maskedWebhookSecret: string;
}

export interface AuditEvent {
  time: string;
  actor: string;
  action: string;
  result: "Success" | "Failed";
  reason: string;
  reference: string;
}

export interface DiagnosticCheckItem {
  name: string;
  status: "pass" | "fail" | "warn";
  detail: string;
  latency?: string;
}

export interface IntegrationItem {
  id: string;
  name: string;
  category: string;
  provider: string;
  providerShort: string;
  providerLogoType: "npci" | "bbps" | "meta" | "nic" | "uidai" | "netc" | "razorpay" | "airtel" | "nsdl" | "cams" | "setu" | "incometax";
  sahProduct: string;
  sahService: string;
  status: IntegrationStatus;
  sla: string;
  slaTarget: number;
  currentUptime: number;
  p95: number;
  p95Unit: string;
  p95Change: string;
  p95TrendDirection: "up" | "down";
  errorRate: string;
  errorRateChange: string;
  errorRateTrendDirection: "up" | "down";
  volume: string;
  volumeChange: string;
  volumeTrendDirection: "up" | "down";
  description: string;
  environment: string;
  primaryEndpoint: string;
  backupEndpoint: string;
  webhookCallback: "Enabled" | "Disabled";
  region: string;
  version: string;
  workspacesCount: number;
  sparkline: number[];
  latencySeries: { time: string; p95: number }[];
  errorSeries: { time: string; rate: number }[];
  volumeSeries: { time: string; reqs: number }[];
  metricsBreakdown: {
    p50: number;
    p95: number;
    p99: number;
    errorRate: number;
    successRate: number;
    requestVolume: string;
    timeoutRate: number;
  };
  endpoints: IntegrationEndpoint[];
  dependentServices: DependentService[];
  workspaces: WorkspaceUsage[];
  recentIssues: IntegrationIssue[];
  configuration: SafeConfiguration;
  auditTrail: AuditEvent[];
  diagnosticChecks: DiagnosticCheckItem[];
}

export const MOCK_INTEGRATIONS: IntegrationItem[] = [
  {
    id: "npci-upi",
    name: "NPCI UPI Switch",
    category: "Payment Rail",
    provider: "NPCI",
    providerShort: "NPCI",
    providerLogoType: "npci",
    sahProduct: "BoSS",
    sahService: "UPI Payment Service",
    status: "Healthy",
    sla: "99.99%",
    slaTarget: 99.99,
    currentUptime: 99.997,
    p95: 18,
    p95Unit: "ms",
    p95Change: "↓ 22%",
    p95TrendDirection: "down",
    errorRate: "0.01%",
    errorRateChange: "↓ 60%",
    errorRateTrendDirection: "down",
    volume: "1.2K req/min",
    volumeChange: "↑ 15%",
    volumeTrendDirection: "up",
    description: "Handles UPI transaction routing, authorization and settlement across all partner banks.",
    environment: "Production",
    primaryEndpoint: "https://api.npci.org.in/upi",
    backupEndpoint: "https://dr-api.npci.org.in/upi",
    webhookCallback: "Enabled",
    region: "India (Primary)",
    version: "v3.1.0",
    workspacesCount: 124,
    sparkline: [22, 19, 18, 17, 24, 18, 19, 18, 17, 18],
    latencySeries: [
      { time: "09:30", p95: 19 },
      { time: "09:40", p95: 22 },
      { time: "09:50", p95: 18 },
      { time: "10:00", p95: 25 },
      { time: "10:10", p95: 17 },
      { time: "10:20", p95: 18 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.02 },
      { time: "09:40", rate: 0.01 },
      { time: "09:50", rate: 0.03 },
      { time: "10:00", rate: 0.01 },
      { time: "10:10", rate: 0.01 },
      { time: "10:20", rate: 0.01 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 1100 },
      { time: "09:40", reqs: 1250 },
      { time: "09:50", reqs: 1180 },
      { time: "10:00", reqs: 1320 },
      { time: "10:10", reqs: 1210 },
      { time: "10:20", reqs: 1280 },
    ],
    metricsBreakdown: {
      p50: 12,
      p95: 18,
      p99: 34,
      errorRate: 0.01,
      successRate: 99.99,
      requestVolume: "1.2K req/min",
      timeoutRate: 0.002,
    },
    endpoints: [
      {
        method: "POST",
        path: "https://api.npci.org.in/upi/transaction",
        status: "Healthy",
        p95: 18,
        errorRate: "0.01%",
        reqsPerMin: "1.2K/min",
      },
      {
        method: "POST",
        path: "https://api.npci.org.in/upi/settlement",
        status: "Healthy",
        p95: 24,
        errorRate: "0.00%",
        reqsPerMin: "180/min",
      },
      {
        method: "GET",
        path: "https://api.npci.org.in/upi/vpa/verify",
        status: "Healthy",
        p95: 14,
        errorRate: "0.00%",
        reqsPerMin: "850/min",
      },
      {
        method: "POST",
        path: "https://api.npci.org.in/upi/refund",
        status: "Healthy",
        p95: 22,
        errorRate: "0.02%",
        reqsPerMin: "45/min",
      },
      {
        method: "GET",
        path: "https://api.npci.org.in/upi/health",
        status: "Healthy",
        p95: 8,
        errorRate: "0.00%",
        reqsPerMin: "60/min",
      },
    ],
    dependentServices: [
      {
        name: "UPI Authorization Service",
        status: "Healthy",
        p95: 14,
        errorRate: "0.01%",
        lastCheck: "30s ago",
        product: "BoSS",
      },
      {
        name: "Settlement Service",
        status: "Healthy",
        p95: 28,
        errorRate: "0.00%",
        lastCheck: "1m ago",
        product: "BoSS",
      },
      {
        name: "Partner Bank Connectivity",
        status: "Healthy",
        p95: 22,
        errorRate: "0.02%",
        lastCheck: "45s ago",
        product: "Sahayogi Cloud",
      },
      {
        name: "Core API Gateway",
        status: "Healthy",
        p95: 4,
        errorRate: "0.00%",
        lastCheck: "15s ago",
        product: "Sahayogi One",
      },
    ],
    workspaces: [
      {
        name: "Sharma Traders",
        wsId: "WS-94812",
        product: "Chat with Sahayogi",
        status: "Healthy",
        txVolume: "420 tx/hr",
        lastActive: "2 mins ago",
      },
      {
        name: "Bharat Agro",
        wsId: "WS-77310",
        product: "BoSS",
        status: "Healthy",
        txVolume: "1.1K tx/hr",
        lastActive: "Just now",
      },
      {
        name: "Kalyan Logistics",
        wsId: "WS-77211",
        product: "Sahayogi Cloud",
        status: "Healthy",
        txVolume: "290 tx/hr",
        lastActive: "5 mins ago",
      },
      {
        name: "Apex Healthcare",
        wsId: "WS-88104",
        product: "Office Sahayogi",
        status: "Healthy",
        txVolume: "610 tx/hr",
        lastActive: "1 min ago",
      },
      {
        name: "Zenith Financial",
        wsId: "WS-66291",
        product: "Investor Sahayogi",
        status: "Healthy",
        txVolume: "850 tx/hr",
        lastActive: "Just now",
      },
      {
        name: "TaxPro Consultants",
        wsId: "WS-54120",
        product: "Tax Sahayogi",
        status: "Healthy",
        txVolume: "340 tx/hr",
        lastActive: "12 mins ago",
      },
    ],
    recentIssues: [
      {
        date: "28 Sep 2026, 14:15",
        issue: "UPI transaction latency spike across partner switch",
        severity: "Low",
        status: "Resolved",
        affectedWorkspaces: 12,
      },
      {
        date: "27 Sep 2026, 09:30",
        issue: "Partner bank HDFC switch intermittent 504 timeout",
        severity: "Medium",
        status: "Resolved",
        affectedWorkspaces: 8,
      },
      {
        date: "25 Sep 2026, 18:22",
        issue: "Settlement API latency increase during peak clearing batch",
        severity: "Low",
        status: "Resolved",
        affectedWorkspaces: 18,
      },
    ],
    configuration: {
      provider: "NPCI",
      environment: "Production",
      region: "India (Primary - Mumbai AWS ap-south-1)",
      primaryEndpoint: "https://api.npci.org.in/upi",
      backupEndpoint: "https://dr-api.npci.org.in/upi",
      maskedCredential: "npci_prod_••••••82",
      credentialStatus: "Valid (Expires in 184 days)",
      lastValidation: "28 Sep 2026, 10:42",
      tlsCipher: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/npci",
      maskedWebhookSecret: "whsec_••••••••41b8",
    },
    auditTrail: [
      {
        time: "10:42",
        actor: "System",
        action: "INTEGRATION_HEALTH_CHECK",
        result: "Success",
        reason: "Scheduled automated probe returned HTTP 200 OK",
        reference: "CHK-99104",
      },
      {
        time: "09:18",
        actor: "dhruv.singla@setu.co",
        action: "INTEGRATION_CONFIGURATION_UPDATED",
        result: "Success",
        reason: "Adjusted gateway timeout threshold to 3500ms for festive volume",
        reference: "CFG-44021",
      },
      {
        time: "27 Sep",
        actor: "System",
        action: "PROVIDER_HEALTH_CHECK",
        result: "Success",
        reason: "NPCI core cert renewed and verified against HSM trust store",
        reference: "SEC-10924",
      },
      {
        time: "26 Sep",
        actor: "automated-sync",
        action: "ENDPOINT_DISCOVERY_SYNC",
        result: "Success",
        reason: "Synced OpenAPI schema v3.1.0 without breaking changes",
        reference: "API-88319",
      },
    ],
    diagnosticChecks: [
      { name: "DNS & Edge Routing", status: "pass", latency: "4 ms", detail: "Resolved to 103.241.136.25 via Mumbai CDN" },
      { name: "TLS 1.3 Certificate & Handshake", status: "pass", latency: "12 ms", detail: "Valid cert (DigiCert High Assurance, exp Nov 2027)" },
      { name: "Endpoint Reachability", status: "pass", latency: "18 ms", detail: "HTTP 200 OK received on /upi/health" },
      { name: "Provider Network Health", status: "pass", latency: "14 ms", detail: "NPCI switch status nominal across all regional nodes" },
      { name: "Payload Schema & Response Validation", status: "pass", latency: "18 ms", detail: "HMAC signed response payload verified" },
    ],
  },
  {
    id: "npci-bbps",
    name: "NPCI Bharat BillPay (BBPS)",
    category: "Biller Network",
    provider: "Bharat BillPay",
    providerShort: "Bharat BillPay",
    providerLogoType: "bbps",
    sahProduct: "BoSS",
    sahService: "BBPS Bill Payments Switch",
    status: "Healthy",
    sla: "99.95%",
    slaTarget: 99.95,
    currentUptime: 99.98,
    p95: 24,
    p95Unit: "ms",
    p95Change: "↓ 10%",
    p95TrendDirection: "down",
    errorRate: "0.02%",
    errorRateChange: "↓ 20%",
    errorRateTrendDirection: "down",
    volume: "850 req/min",
    volumeChange: "↑ 8%",
    volumeTrendDirection: "up",
    description: "Centralized bill payment network connecting 20,000+ utility billers and recurring payment collectors.",
    environment: "Production",
    primaryEndpoint: "https://api.bbps.npci.org.in/v2/billers",
    backupEndpoint: "https://dr-api.bbps.npci.org.in/v2/billers",
    webhookCallback: "Enabled",
    region: "India (Primary)",
    version: "v2.4.1",
    workspacesCount: 96,
    sparkline: [26, 24, 25, 23, 24, 25, 24, 23, 24, 24],
    latencySeries: [
      { time: "09:30", p95: 24 },
      { time: "09:40", p95: 25 },
      { time: "09:50", p95: 23 },
      { time: "10:00", p95: 26 },
      { time: "10:10", p95: 24 },
      { time: "10:20", p95: 24 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.02 },
      { time: "09:40", rate: 0.02 },
      { time: "09:50", rate: 0.01 },
      { time: "10:00", rate: 0.03 },
      { time: "10:10", rate: 0.02 },
      { time: "10:20", rate: 0.02 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 820 },
      { time: "09:40", reqs: 860 },
      { time: "09:50", reqs: 840 },
      { time: "10:00", reqs: 890 },
      { time: "10:10", reqs: 850 },
      { time: "10:20", reqs: 870 },
    ],
    metricsBreakdown: {
      p50: 16,
      p95: 24,
      p99: 45,
      errorRate: 0.02,
      successRate: 99.98,
      requestVolume: "850 req/min",
      timeoutRate: 0.005,
    },
    endpoints: [
      { method: "GET", path: "https://api.bbps.npci.org.in/v2/billers", status: "Healthy", p95: 24, errorRate: "0.02%", reqsPerMin: "450/min" },
      { method: "POST", path: "https://api.bbps.npci.org.in/v2/fetch-bill", status: "Healthy", p95: 28, errorRate: "0.01%", reqsPerMin: "320/min" },
      { method: "POST", path: "https://api.bbps.npci.org.in/v2/pay", status: "Healthy", p95: 32, errorRate: "0.03%", reqsPerMin: "80/min" },
    ],
    dependentServices: [
      { name: "BBPS Bill Ingestion Engine", status: "Healthy", p95: 18, errorRate: "0.01%", lastCheck: "1m ago", product: "BoSS" },
      { name: "Utility Biller Directory Sync", status: "Healthy", p95: 22, errorRate: "0.00%", lastCheck: "3m ago", product: "BoSS" },
    ],
    workspaces: [
      { name: "Bharat Agro", wsId: "WS-77310", product: "BoSS", status: "Healthy", txVolume: "350 tx/hr", lastActive: "Just now" },
      { name: "Apex Healthcare", wsId: "WS-88104", product: "Office Sahayogi", status: "Healthy", txVolume: "180 tx/hr", lastActive: "4 mins ago" },
    ],
    recentIssues: [
      { date: "24 Sep 2026, 11:00", issue: "Electricity discom bill fetch timeout in BESCOM zone", severity: "Low", status: "Resolved", affectedWorkspaces: 4 },
    ],
    configuration: {
      provider: "Bharat BillPay",
      environment: "Production",
      region: "India (Primary - Mumbai)",
      primaryEndpoint: "https://api.bbps.npci.org.in/v2/billers",
      backupEndpoint: "https://dr-api.bbps.npci.org.in/v2/billers",
      maskedCredential: "bbps_prod_••••••19",
      credentialStatus: "Valid (Expires in 220 days)",
      lastValidation: "28 Sep 2026, 08:30",
      tlsCipher: "TLS_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/bbps",
      maskedWebhookSecret: "whsec_••••••••8819",
    },
    auditTrail: [
      { time: "08:30", actor: "System", action: "INTEGRATION_HEALTH_CHECK", result: "Success", reason: "Biller sync active", reference: "CHK-88190" },
    ],
    diagnosticChecks: [
      { name: "DNS Resolution", status: "pass", latency: "5 ms", detail: "DNS resolved to NPCI BBPS gateway IP" },
      { name: "TLS Handshake", status: "pass", latency: "14 ms", detail: "Valid cert (exp Jan 2028)" },
      { name: "Biller Registry Ping", status: "pass", latency: "24 ms", detail: "20,412 active billers synced" },
    ],
  },
  {
    id: "meta-waba",
    name: "Meta WhatsApp Cloud API",
    category: "Messaging Bridge",
    provider: "Meta (WABA)",
    providerShort: "Meta",
    providerLogoType: "meta",
    sahProduct: "Chat with Sahayogi",
    sahService: "WhatsApp Messaging Gateway",
    status: "Degraded",
    sla: "97.40%",
    slaTarget: 99.50,
    currentUptime: 97.40,
    p95: 840,
    p95Unit: "ms",
    p95Change: "↑ 140%",
    p95TrendDirection: "up",
    errorRate: "2.14%",
    errorRateChange: "↑ 180%",
    errorRateTrendDirection: "up",
    volume: "2.8K msg/min",
    volumeChange: "↑ 4%",
    volumeTrendDirection: "up",
    description: "Business messaging bridge for WhatsApp conversational AI, invoice dispatch, and interactive order booking.",
    environment: "Production",
    primaryEndpoint: "https://graph.facebook.com/v21.0",
    backupEndpoint: "https://graph.facebook.com/v20.0",
    webhookCallback: "Enabled",
    region: "Global / Singapore Edge",
    version: "v21.0",
    workspacesCount: 310,
    sparkline: [340, 420, 580, 710, 840, 890, 820, 850, 840, 840],
    latencySeries: [
      { time: "09:30", p95: 380 },
      { time: "09:40", p95: 540 },
      { time: "09:50", p95: 720 },
      { time: "10:00", p95: 890 },
      { time: "10:10", p95: 820 },
      { time: "10:20", p95: 840 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.45 },
      { time: "09:40", rate: 0.92 },
      { time: "09:50", rate: 1.60 },
      { time: "10:00", rate: 2.35 },
      { time: "10:10", rate: 2.18 },
      { time: "10:20", rate: 2.14 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 2600 },
      { time: "09:40", reqs: 2750 },
      { time: "09:50", reqs: 2800 },
      { time: "10:00", reqs: 2920 },
      { time: "10:10", reqs: 2850 },
      { time: "10:20", reqs: 2800 },
    ],
    metricsBreakdown: {
      p50: 310,
      p95: 840,
      p99: 1450,
      errorRate: 2.14,
      successRate: 97.86,
      requestVolume: "2.8K msg/min",
      timeoutRate: 0.42,
    },
    endpoints: [
      { method: "POST", path: "https://graph.facebook.com/v21.0/messages", status: "Degraded", p95: 840, errorRate: "2.14%", reqsPerMin: "2.2K/min" },
      { method: "POST", path: "https://graph.facebook.com/v21.0/media", status: "Healthy", p95: 420, errorRate: "0.10%", reqsPerMin: "450/min" },
      { method: "GET", path: "https://graph.facebook.com/v21.0/business_profile", status: "Healthy", p95: 180, errorRate: "0.00%", reqsPerMin: "150/min" },
    ],
    dependentServices: [
      { name: "WhatsApp Gateway Egress", status: "Degraded", p95: 840, errorRate: "2.14%", lastCheck: "10s ago", product: "Chat with Sahayogi" },
      { name: "Template Notification Dispatcher", status: "Attention", p95: 450, errorRate: "0.85%", lastCheck: "40s ago", product: "Chat with Sahayogi" },
      { name: "Media Attachment Converter", status: "Healthy", p95: 220, errorRate: "0.01%", lastCheck: "1m ago", product: "Chat with Sahayogi" },
    ],
    workspaces: [
      { name: "Sharma Traders", wsId: "WS-94812", product: "Chat with Sahayogi", status: "Degraded", txVolume: "940 msg/hr", lastActive: "Just now" },
      { name: "Kalyan Logistics", wsId: "WS-77211", product: "Sahayogi Cloud", status: "Healthy", txVolume: "320 msg/hr", lastActive: "1 min ago" },
      { name: "UrbanMart Retail", wsId: "WS-33104", product: "Chat with Sahayogi", status: "Attention", txVolume: "510 msg/hr", lastActive: "2 mins ago" },
    ],
    recentIssues: [
      { date: "28 Sep 2026, 09:40", issue: "OAuth token expiration alert on WS-94812 causing 401 unauth errors", severity: "High", status: "Investigating", affectedWorkspaces: 14 },
      { date: "26 Sep 2026, 16:20", issue: "Meta Graph API regional gateway elevated latency in APAC", severity: "Medium", status: "Resolved", affectedWorkspaces: 48 },
    ],
    configuration: {
      provider: "Meta (WABA)",
      environment: "Production",
      region: "Global / Singapore Edge",
      primaryEndpoint: "https://graph.facebook.com/v21.0",
      backupEndpoint: "https://graph.facebook.com/v20.0",
      maskedCredential: "waba_prod_••••••9a",
      credentialStatus: "Degraded (Token refresh pending on 1 workspace)",
      lastValidation: "28 Sep 2026, 10:15",
      tlsCipher: "TLS_CHACHA20_POLY1305_SHA256",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/meta",
      maskedWebhookSecret: "whsec_••••••••9104",
    },
    auditTrail: [
      { time: "10:15", actor: "System", action: "TOKEN_EXPIRY_WARNING", result: "Failed", reason: "Token for WS-94812 expires in <2 hours", reference: "SEC-99014" },
      { time: "09:40", actor: "dhruv.singla@setu.co", action: "GATEWAY_TRAFFIC_REROUTE", result: "Success", reason: "Routed media outbound traffic to Singapore proxy", reference: "RTE-33104" },
    ],
    diagnosticChecks: [
      { name: "DNS & Edge Routing", status: "pass", latency: "14 ms", detail: "Edge CDN routing nominal" },
      { name: "TLS 1.3 Handshake", status: "pass", latency: "18 ms", detail: "Valid Meta certificate" },
      { name: "OAuth Token Validation", status: "warn", latency: "840 ms", detail: "Token expired on WS-94812, remaining 309 workspaces valid" },
      { name: "Webhook Delivery Queue", status: "warn", latency: "420 ms", detail: "DLQ queue has 14 queued retries" },
    ],
  },
  {
    id: "nic-gst",
    name: "NIC GSTN Ingestion Portal",
    category: "Tax Government API",
    provider: "NIC",
    providerShort: "NIC",
    providerLogoType: "nic",
    sahProduct: "Tax Sahayogi",
    sahService: "GSTN Ingestion & E-Way",
    status: "Healthy",
    sla: "99.80%",
    slaTarget: 99.80,
    currentUptime: 99.85,
    p95: 42,
    p95Unit: "ms",
    p95Change: "↓ 5%",
    p95TrendDirection: "down",
    errorRate: "0.05%",
    errorRateChange: "↓ 12%",
    errorRateTrendDirection: "down",
    volume: "640 req/min",
    volumeChange: "↑ 22%",
    volumeTrendDirection: "up",
    description: "Government tax portal for GST return filing, E-Way bill generation, and invoice registration (IRN).",
    environment: "Production",
    primaryEndpoint: "https://api.gstn.nic.in/v1.0",
    backupEndpoint: "https://e-waybill.nic.in/api",
    webhookCallback: "Disabled",
    region: "India (New Delhi)",
    version: "v1.4.2",
    workspacesCount: 188,
    sparkline: [44, 42, 45, 41, 42, 43, 42, 41, 42, 42],
    latencySeries: [
      { time: "09:30", p95: 44 },
      { time: "09:40", p95: 42 },
      { time: "09:50", p95: 45 },
      { time: "10:00", p95: 41 },
      { time: "10:10", p95: 42 },
      { time: "10:20", p95: 42 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.06 },
      { time: "09:40", rate: 0.05 },
      { time: "09:50", rate: 0.04 },
      { time: "10:00", rate: 0.05 },
      { time: "10:10", rate: 0.05 },
      { time: "10:20", rate: 0.05 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 600 },
      { time: "09:40", reqs: 620 },
      { time: "09:50", reqs: 640 },
      { time: "10:00", reqs: 670 },
      { time: "10:10", reqs: 630 },
      { time: "10:20", reqs: 640 },
    ],
    metricsBreakdown: {
      p50: 28,
      p95: 42,
      p99: 88,
      errorRate: 0.05,
      successRate: 99.95,
      requestVolume: "640 req/min",
      timeoutRate: 0.01,
    },
    endpoints: [
      { method: "POST", path: "https://api.gstn.nic.in/v1.0/einvoice/generate", status: "Healthy", p95: 42, errorRate: "0.05%", reqsPerMin: "340/min" },
      { method: "POST", path: "https://api.gstn.nic.in/v1.0/ewaybill/create", status: "Healthy", p95: 38, errorRate: "0.02%", reqsPerMin: "210/min" },
      { method: "GET", path: "https://api.gstn.nic.in/v1.0/taxpayer/search", status: "Healthy", p95: 22, errorRate: "0.00%", reqsPerMin: "90/min" },
    ],
    dependentServices: [
      { name: "GST E-Way Bill Generator", status: "Healthy", p95: 36, errorRate: "0.04%", lastCheck: "1m ago", product: "Tax Sahayogi" },
      { name: "IRN Digital Signature Vault", status: "Healthy", p95: 18, errorRate: "0.00%", lastCheck: "2m ago", product: "Tax Sahayogi" },
    ],
    workspaces: [
      { name: "TaxPro Consultants", wsId: "WS-54120", product: "Tax Sahayogi", status: "Healthy", txVolume: "380 inv/hr", lastActive: "Just now" },
      { name: "Bharat Agro", wsId: "WS-77310", product: "BoSS", status: "Healthy", txVolume: "140 inv/hr", lastActive: "3 mins ago" },
    ],
    recentIssues: [
      { date: "22 Sep 2026, 14:00", issue: "NIC scheduled weekend maintenance e-Way bill sync pause", severity: "Low", status: "Resolved", affectedWorkspaces: 80 },
    ],
    configuration: {
      provider: "NIC",
      environment: "Production",
      region: "India (New Delhi)",
      primaryEndpoint: "https://api.gstn.nic.in/v1.0",
      backupEndpoint: "https://e-waybill.nic.in/api",
      maskedCredential: "nic_gst_••••••77",
      credentialStatus: "Valid (Expires in 98 days)",
      lastValidation: "28 Sep 2026, 06:00",
      tlsCipher: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      webhookEndpoint: "Disabled by Provider",
      maskedWebhookSecret: "—",
    },
    auditTrail: [
      { time: "06:00", actor: "System", action: "HEALTH_CHECK", result: "Success", reason: "NIC e-Invoice portal response nominal", reference: "CHK-77401" },
    ],
    diagnosticChecks: [
      { name: "NIC Gateway Ping", status: "pass", latency: "12 ms", detail: "HTTP 200 OK from NIC NDC Delhi" },
      { name: "IRN Signature Trust", status: "pass", latency: "8 ms", detail: "Government root CA valid" },
    ],
  },
  {
    id: "uidai",
    name: "UIDAI Aadhaar / DigiLocker",
    category: "Identity & KYC",
    provider: "UIDAI / NSDL",
    providerShort: "UIDAI",
    providerLogoType: "uidai",
    sahProduct: "Sahayogi One",
    sahService: "KYC & Identity Verification",
    status: "Attention",
    sla: "98.90%",
    slaTarget: 99.50,
    currentUptime: 98.92,
    p95: 320,
    p95Unit: "ms",
    p95Change: "↑ 45%",
    p95TrendDirection: "up",
    errorRate: "0.85%",
    errorRateChange: "↑ 35%",
    errorRateTrendDirection: "up",
    volume: "420 req/min",
    volumeChange: "↑ 12%",
    volumeTrendDirection: "up",
    description: "Identity verification rail for Aadhaar OTP eKYC, biometric auth, and DigiLocker verifiable credentials.",
    environment: "Production",
    primaryEndpoint: "https://auth.uidai.gov.in/v2.5",
    backupEndpoint: "https://digilocker.gov.in/public/api",
    webhookCallback: "Enabled",
    region: "India (Manesar)",
    version: "v2.5.0",
    workspacesCount: 142,
    sparkline: [220, 240, 280, 310, 340, 330, 320, 310, 320, 320],
    latencySeries: [
      { time: "09:30", p95: 240 },
      { time: "09:40", p95: 280 },
      { time: "09:50", p95: 340 },
      { time: "10:00", p95: 330 },
      { time: "10:10", p95: 310 },
      { time: "10:20", p95: 320 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.50 },
      { time: "09:40", rate: 0.65 },
      { time: "09:50", rate: 0.95 },
      { time: "10:00", rate: 0.88 },
      { time: "10:10", rate: 0.82 },
      { time: "10:20", rate: 0.85 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 390 },
      { time: "09:40", reqs: 410 },
      { time: "09:50", reqs: 430 },
      { time: "10:00", reqs: 440 },
      { time: "10:10", reqs: 420 },
      { time: "10:20", reqs: 420 },
    ],
    metricsBreakdown: {
      p50: 180,
      p95: 320,
      p99: 680,
      errorRate: 0.85,
      successRate: 99.15,
      requestVolume: "420 req/min",
      timeoutRate: 0.12,
    },
    endpoints: [
      { method: "POST", path: "https://auth.uidai.gov.in/v2.5/otp", status: "Attention", p95: 320, errorRate: "0.85%", reqsPerMin: "280/min" },
      { method: "POST", path: "https://digilocker.gov.in/public/api/v1/xml", status: "Healthy", p95: 140, errorRate: "0.02%", reqsPerMin: "140/min" },
    ],
    dependentServices: [
      { name: "Aadhaar eKYC Verification", status: "Attention", p95: 320, errorRate: "0.85%", lastCheck: "30s ago", product: "Sahayogi One" },
      { name: "DigiLocker Doc Pull Service", status: "Healthy", p95: 120, errorRate: "0.01%", lastCheck: "2m ago", product: "Sahayogi One" },
    ],
    workspaces: [
      { name: "Zenith Financial", wsId: "WS-66291", product: "Investor Sahayogi", status: "Attention", txVolume: "140 kyc/hr", lastActive: "Just now" },
      { name: "Sharma Traders", wsId: "WS-94812", product: "Chat with Sahayogi", status: "Healthy", txVolume: "45 kyc/hr", lastActive: "5 mins ago" },
    ],
    recentIssues: [
      { date: "28 Sep 2026, 08:15", issue: "UIDAI OTP dispatch latency elevated in Maharashtra & Gujarat telecom circle", severity: "Medium", status: "Monitoring", affectedWorkspaces: 24 },
    ],
    configuration: {
      provider: "UIDAI / NSDL",
      environment: "Production",
      region: "India (Manesar Data Center)",
      primaryEndpoint: "https://auth.uidai.gov.in/v2.5",
      backupEndpoint: "https://digilocker.gov.in/public/api",
      maskedCredential: "uidai_prod_••••••41",
      credentialStatus: "Valid (Expires in 140 days)",
      lastValidation: "28 Sep 2026, 09:00",
      tlsCipher: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/uidai",
      maskedWebhookSecret: "whsec_••••••••3310",
    },
    auditTrail: [
      { time: "09:00", actor: "System", action: "KYC_HEALTH_CHECK", result: "Success", reason: "DigiLocker and UIDAI ASA connection nominal", reference: "CHK-33104" },
    ],
    diagnosticChecks: [
      { name: "ASA Gateway Tunnel", status: "pass", latency: "16 ms", detail: "Direct MPLS link to UIDAI active" },
      { name: "OTP Delivery Monitor", status: "warn", latency: "320 ms", detail: "Elevated carrier queue on Vodafone Idea circle" },
    ],
  },
  {
    id: "netc-fasttag",
    name: "NETC FastTag Transit Rail",
    category: "Toll Network",
    provider: "NETC",
    providerShort: "NETC",
    providerLogoType: "netc",
    sahProduct: "Sahayogi Cloud",
    sahService: "FastTag Transit Fleet Sync",
    status: "Healthy",
    sla: "99.98%",
    slaTarget: 99.95,
    currentUptime: 99.99,
    p95: 29,
    p95Unit: "ms",
    p95Change: "↓ 8%",
    p95TrendDirection: "down",
    errorRate: "0.01%",
    errorRateChange: "↓ 40%",
    errorRateTrendDirection: "down",
    volume: "380 req/min",
    volumeChange: "↑ 18%",
    volumeTrendDirection: "up",
    description: "National Electronic Toll Collection switch for vehicle RFID tracking, toll clearance, and parking fee transit.",
    environment: "Production",
    primaryEndpoint: "https://api.netc.org.in/transit/v1",
    backupEndpoint: "https://dr-api.netc.org.in/transit/v1",
    webhookCallback: "Enabled",
    region: "India (Primary)",
    version: "v1.2.0",
    workspacesCount: 64,
    sparkline: [31, 29, 30, 28, 29, 30, 29, 28, 29, 29],
    latencySeries: [
      { time: "09:30", p95: 31 },
      { time: "09:40", p95: 29 },
      { time: "09:50", p95: 30 },
      { time: "10:00", p95: 28 },
      { time: "10:10", p95: 29 },
      { time: "10:20", p95: 29 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.01 },
      { time: "09:40", rate: 0.01 },
      { time: "09:50", rate: 0.01 },
      { time: "10:00", rate: 0.01 },
      { time: "10:10", rate: 0.01 },
      { time: "10:20", rate: 0.01 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 360 },
      { time: "09:40", reqs: 370 },
      { time: "09:50", reqs: 385 },
      { time: "10:00", reqs: 390 },
      { time: "10:10", reqs: 375 },
      { time: "10:20", reqs: 380 },
    ],
    metricsBreakdown: {
      p50: 19,
      p95: 29,
      p99: 52,
      errorRate: 0.01,
      successRate: 99.99,
      requestVolume: "380 req/min",
      timeoutRate: 0.003,
    },
    endpoints: [
      { method: "POST", path: "https://api.netc.org.in/transit/v1/clearance", status: "Healthy", p95: 29, errorRate: "0.01%", reqsPerMin: "280/min" },
      { method: "GET", path: "https://api.netc.org.in/transit/v1/tag-status", status: "Healthy", p95: 18, errorRate: "0.00%", reqsPerMin: "100/min" },
    ],
    dependentServices: [
      { name: "Fleet Toll Sync Engine", status: "Healthy", p95: 22, errorRate: "0.01%", lastCheck: "45s ago", product: "Sahayogi Cloud" },
    ],
    workspaces: [
      { name: "Kalyan Logistics", wsId: "WS-77211", product: "Sahayogi Cloud", status: "Healthy", txVolume: "290 tx/hr", lastActive: "Just now" },
    ],
    recentIssues: [],
    configuration: {
      provider: "NETC",
      environment: "Production",
      region: "India (Primary)",
      primaryEndpoint: "https://api.netc.org.in/transit/v1",
      backupEndpoint: "https://dr-api.netc.org.in/transit/v1",
      maskedCredential: "netc_prod_••••••55",
      credentialStatus: "Valid (Expires in 310 days)",
      lastValidation: "28 Sep 2026, 09:30",
      tlsCipher: "TLS_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/netc",
      maskedWebhookSecret: "whsec_••••••••7741",
    },
    auditTrail: [
      { time: "09:30", actor: "System", action: "HEALTH_CHECK", result: "Success", reason: "Toll plaza clearance sync nominal", reference: "CHK-55104" },
    ],
    diagnosticChecks: [
      { name: "NETC Transit Probe", status: "pass", latency: "10 ms", detail: "All 1,200 NHAI toll plazas reachable" },
    ],
  },
  {
    id: "razorpay",
    name: "Razorpay Aggregator Rail",
    category: "Payment Gateway",
    provider: "Razorpay",
    providerShort: "Razorpay",
    providerLogoType: "razorpay",
    sahProduct: "BoSS",
    sahService: "Card & NetBanking Checkout",
    status: "Healthy",
    sla: "99.92%",
    slaTarget: 99.90,
    currentUptime: 99.94,
    p95: 74,
    p95Unit: "ms",
    p95Change: "↓ 15%",
    p95TrendDirection: "down",
    errorRate: "0.04%",
    errorRateChange: "↓ 25%",
    errorRateTrendDirection: "down",
    volume: "1.5K req/min",
    volumeChange: "↑ 10%",
    volumeTrendDirection: "up",
    description: "Payment gateway aggregator for Credit/Debit cards, NetBanking, international payments, and subscription mandates.",
    environment: "Production",
    primaryEndpoint: "https://api.razorpay.com/v1",
    backupEndpoint: "https://api-backup.razorpay.com/v1",
    webhookCallback: "Enabled",
    region: "India (Mumbai)",
    version: "v1.0.0",
    workspacesCount: 205,
    sparkline: [78, 76, 75, 73, 75, 74, 73, 74, 75, 74],
    latencySeries: [
      { time: "09:30", p95: 78 },
      { time: "09:40", p95: 76 },
      { time: "09:50", p95: 73 },
      { time: "10:00", p95: 75 },
      { time: "10:10", p95: 74 },
      { time: "10:20", p95: 74 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.05 },
      { time: "09:40", rate: 0.04 },
      { time: "09:50", rate: 0.03 },
      { time: "10:00", rate: 0.04 },
      { time: "10:10", rate: 0.04 },
      { time: "10:20", rate: 0.04 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 1450 },
      { time: "09:40", reqs: 1480 },
      { time: "09:50", reqs: 1520 },
      { time: "10:00", reqs: 1550 },
      { time: "10:10", reqs: 1500 },
      { time: "10:20", reqs: 1510 },
    ],
    metricsBreakdown: {
      p50: 48,
      p95: 74,
      p99: 130,
      errorRate: 0.04,
      successRate: 99.96,
      requestVolume: "1.5K req/min",
      timeoutRate: 0.008,
    },
    endpoints: [
      { method: "POST", path: "https://api.razorpay.com/v1/orders", status: "Healthy", p95: 64, errorRate: "0.02%", reqsPerMin: "900/min" },
      { method: "POST", path: "https://api.razorpay.com/v1/payments", status: "Healthy", p95: 82, errorRate: "0.05%", reqsPerMin: "520/min" },
      { method: "POST", path: "https://api.razorpay.com/v1/refunds", status: "Healthy", p95: 72, errorRate: "0.01%", reqsPerMin: "80/min" },
    ],
    dependentServices: [
      { name: "Checkout Order Service", status: "Healthy", p95: 54, errorRate: "0.03%", lastCheck: "20s ago", product: "BoSS" },
      { name: "Webhook Dispatch Processor", status: "Healthy", p95: 28, errorRate: "0.00%", lastCheck: "1m ago", product: "BoSS" },
    ],
    workspaces: [
      { name: "Bharat Agro", wsId: "WS-77310", product: "BoSS", status: "Healthy", txVolume: "780 ord/hr", lastActive: "Just now" },
      { name: "UrbanMart Retail", wsId: "WS-33104", product: "Chat with Sahayogi", status: "Healthy", txVolume: "420 ord/hr", lastActive: "1 min ago" },
    ],
    recentIssues: [],
    configuration: {
      provider: "Razorpay",
      environment: "Production",
      region: "India (Mumbai)",
      primaryEndpoint: "https://api.razorpay.com/v1",
      backupEndpoint: "https://api-backup.razorpay.com/v1",
      maskedCredential: "rzp_live_••••••99",
      credentialStatus: "Valid (Key rotated 30 days ago)",
      lastValidation: "28 Sep 2026, 10:00",
      tlsCipher: "TLS_AES_128_GCM_SHA256",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/razorpay",
      maskedWebhookSecret: "whsec_••••••••1104",
    },
    auditTrail: [
      { time: "10:00", actor: "System", action: "HEALTH_CHECK", result: "Success", reason: "Webhook delivery SLA met", reference: "CHK-11044" },
    ],
    diagnosticChecks: [
      { name: "Razorpay API Ping", status: "pass", latency: "22 ms", detail: "HTTP 200 OK from Mumbai region" },
      { name: "Webhook Signature Test", status: "pass", latency: "6 ms", detail: "Secret verified against test payload" },
    ],
  },
  {
    id: "sms-gateway",
    name: "SMS & OTP Gateway",
    category: "Messaging Provider",
    provider: "Airtel / SMS Provider",
    providerShort: "Airtel",
    providerLogoType: "airtel",
    sahProduct: "Office Sahayogi",
    sahService: "SMS & Notification Dispatch",
    status: "Degraded",
    sla: "98.70%",
    slaTarget: 99.90,
    currentUptime: 98.72,
    p95: 420,
    p95Unit: "ms",
    p95Change: "↑ 88%",
    p95TrendDirection: "up",
    errorRate: "1.80%",
    errorRateChange: "↑ 110%",
    errorRateTrendDirection: "up",
    volume: "920 msg/min",
    volumeChange: "↑ 5%",
    volumeTrendDirection: "up",
    description: "DLT-registered telecom SMS gateway for high-priority 2FA OTPs, transactional alerts, and password resets.",
    environment: "Production",
    primaryEndpoint: "https://api.airtel.in/sms/v2",
    backupEndpoint: "https://backup-sms.airtel.in/v2",
    webhookCallback: "Enabled",
    region: "India (Delhi / Mumbai)",
    version: "v2.1.0",
    workspacesCount: 280,
    sparkline: [210, 240, 280, 350, 420, 450, 430, 410, 420, 420],
    latencySeries: [
      { time: "09:30", p95: 220 },
      { time: "09:40", p95: 260 },
      { time: "09:50", p95: 380 },
      { time: "10:00", p95: 440 },
      { time: "10:10", p95: 410 },
      { time: "10:20", p95: 420 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.60 },
      { time: "09:40", rate: 0.90 },
      { time: "09:50", rate: 1.50 },
      { time: "10:00", rate: 2.10 },
      { time: "10:10", rate: 1.85 },
      { time: "10:20", rate: 1.80 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 880 },
      { time: "09:40", reqs: 910 },
      { time: "09:50", reqs: 940 },
      { time: "10:00", reqs: 950 },
      { time: "10:10", reqs: 920 },
      { time: "10:20", reqs: 920 },
    ],
    metricsBreakdown: {
      p50: 210,
      p95: 420,
      p99: 920,
      errorRate: 1.80,
      successRate: 98.20,
      requestVolume: "920 msg/min",
      timeoutRate: 0.28,
    },
    endpoints: [
      { method: "POST", path: "https://api.airtel.in/sms/v2/send-otp", status: "Degraded", p95: 420, errorRate: "1.80%", reqsPerMin: "680/min" },
      { method: "POST", path: "https://api.airtel.in/sms/v2/transactional", status: "Healthy", p95: 240, errorRate: "0.15%", reqsPerMin: "240/min" },
    ],
    dependentServices: [
      { name: "2FA OTP Dispatch Engine", status: "Degraded", p95: 420, errorRate: "1.80%", lastCheck: "15s ago", product: "Office Sahayogi" },
      { name: "Transactional Alert Dispatcher", status: "Healthy", p95: 180, errorRate: "0.10%", lastCheck: "1m ago", product: "Office Sahayogi" },
    ],
    workspaces: [
      { name: "Apex Healthcare", wsId: "WS-88104", product: "Office Sahayogi", status: "Degraded", txVolume: "340 otp/hr", lastActive: "Just now" },
      { name: "Sharma Traders", wsId: "WS-94812", product: "Chat with Sahayogi", status: "Healthy", txVolume: "120 otp/hr", lastActive: "3 mins ago" },
    ],
    recentIssues: [
      { date: "28 Sep 2026, 09:10", issue: "Airtel primary DLT smsc queue throttling 2FA OTP batch", severity: "High", status: "Investigating", affectedWorkspaces: 32 },
    ],
    configuration: {
      provider: "Airtel / SMS Provider",
      environment: "Production",
      region: "India (Delhi / Mumbai)",
      primaryEndpoint: "https://api.airtel.in/sms/v2",
      backupEndpoint: "https://backup-sms.airtel.in/v2",
      maskedCredential: "airtel_dlt_••••••33",
      credentialStatus: "Valid (DLT Header Principal ID verified)",
      lastValidation: "28 Sep 2026, 09:45",
      tlsCipher: "TLS_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/sms",
      maskedWebhookSecret: "whsec_••••••••4481",
    },
    auditTrail: [
      { time: "09:45", actor: "System", action: "DLT_HEADER_CHECK", result: "Success", reason: "DLT templates compliant with TRAI regulations", reference: "REG-88192" },
    ],
    diagnosticChecks: [
      { name: "Airtel SMPP Link", status: "warn", latency: "420 ms", detail: "Smsc bind active but elevated queue depth (4,120 msgs)" },
    ],
  },
  {
    id: "nsdl-pan",
    name: "NSDL PAN Verification Gateway",
    category: "Identity & KYC",
    provider: "NSDL",
    providerShort: "NSDL",
    providerLogoType: "nsdl",
    sahProduct: "Tax Sahayogi",
    sahService: "PAN Authentication Service",
    status: "Healthy",
    sla: "99.85%",
    slaTarget: 99.80,
    currentUptime: 99.89,
    p95: 48,
    p95Unit: "ms",
    p95Change: "↓ 4%",
    p95TrendDirection: "down",
    errorRate: "0.02%",
    errorRateChange: "↓ 15%",
    errorRateTrendDirection: "down",
    volume: "310 req/min",
    volumeChange: "↑ 6%",
    volumeTrendDirection: "up",
    description: "Direct NSDL online PAN verification and name matching engine for merchant and vendor onboarding.",
    environment: "Production",
    primaryEndpoint: "https://tin.tin.nsdl.com/pan/api/v2",
    backupEndpoint: "https://pan-verify.nsdl.com/api",
    webhookCallback: "Disabled",
    region: "India (Mumbai)",
    version: "v2.0.1",
    workspacesCount: 110,
    sparkline: [52, 49, 48, 47, 49, 48, 47, 48, 48, 48],
    latencySeries: [
      { time: "09:30", p95: 50 },
      { time: "09:40", p95: 49 },
      { time: "09:50", p95: 48 },
      { time: "10:00", p95: 47 },
      { time: "10:10", p95: 48 },
      { time: "10:20", p95: 48 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.03 },
      { time: "09:40", rate: 0.02 },
      { time: "09:50", rate: 0.02 },
      { time: "10:00", rate: 0.02 },
      { time: "10:10", rate: 0.02 },
      { time: "10:20", rate: 0.02 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 290 },
      { time: "09:40", reqs: 300 },
      { time: "09:50", reqs: 310 },
      { time: "10:00", reqs: 320 },
      { time: "10:10", reqs: 310 },
      { time: "10:20", reqs: 310 },
    ],
    metricsBreakdown: {
      p50: 32,
      p95: 48,
      p99: 95,
      errorRate: 0.02,
      successRate: 99.98,
      requestVolume: "310 req/min",
      timeoutRate: 0.004,
    },
    endpoints: [
      { method: "POST", path: "https://tin.tin.nsdl.com/pan/api/v2/verify", status: "Healthy", p95: 48, errorRate: "0.02%", reqsPerMin: "310/min" },
    ],
    dependentServices: [
      { name: "PAN Verification Service", status: "Healthy", p95: 38, errorRate: "0.01%", lastCheck: "2m ago", product: "Tax Sahayogi" },
    ],
    workspaces: [
      { name: "TaxPro Consultants", wsId: "WS-54120", product: "Tax Sahayogi", status: "Healthy", txVolume: "190 vrf/hr", lastActive: "1 min ago" },
    ],
    recentIssues: [],
    configuration: {
      provider: "NSDL",
      environment: "Production",
      region: "India (Mumbai)",
      primaryEndpoint: "https://tin.tin.nsdl.com/pan/api/v2",
      backupEndpoint: "https://pan-verify.nsdl.com/api",
      maskedCredential: "nsdl_tin_••••••90",
      credentialStatus: "Valid (Expires in 210 days)",
      lastValidation: "28 Sep 2026, 07:00",
      tlsCipher: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      webhookEndpoint: "Disabled",
      maskedWebhookSecret: "—",
    },
    auditTrail: [
      { time: "07:00", actor: "System", action: "HEALTH_CHECK", result: "Success", reason: "NSDL TIN portal reachable", reference: "CHK-90182" },
    ],
    diagnosticChecks: [
      { name: "NSDL TIN Server Ping", status: "pass", latency: "14 ms", detail: "HTTP 200 OK from NSDL Mumbai data center" },
    ],
  },
  {
    id: "cams",
    name: "CAMS Mutual Fund Feed",
    category: "Financial Rails",
    provider: "CAMS / KFintech",
    providerShort: "CAMS",
    providerLogoType: "cams",
    sahProduct: "Investor Sahayogi",
    sahService: "Portfolio Statement Sync",
    status: "Healthy",
    sla: "99.91%",
    slaTarget: 99.85,
    currentUptime: 99.93,
    p95: 62,
    p95Unit: "ms",
    p95Change: "↓ 2%",
    p95TrendDirection: "down",
    errorRate: "0.03%",
    errorRateChange: "↓ 8%",
    errorRateTrendDirection: "down",
    volume: "190 req/min",
    volumeChange: "↑ 14%",
    volumeTrendDirection: "up",
    description: "Registrar feed for automated CAS statement ingestion, mutual fund valuation, and portfolio NAV updates.",
    environment: "Production",
    primaryEndpoint: "https://api.camsonline.com/cas/v3",
    backupEndpoint: "https://kfintech.api.com/mf/v1",
    webhookCallback: "Enabled",
    region: "India (Chennai)",
    version: "v3.2.0",
    workspacesCount: 84,
    sparkline: [64, 63, 62, 61, 63, 62, 61, 62, 62, 62],
    latencySeries: [
      { time: "09:30", p95: 64 },
      { time: "09:40", p95: 63 },
      { time: "09:50", p95: 62 },
      { time: "10:00", p95: 61 },
      { time: "10:10", p95: 62 },
      { time: "10:20", p95: 62 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.04 },
      { time: "09:40", rate: 0.03 },
      { time: "09:50", rate: 0.03 },
      { time: "10:00", rate: 0.03 },
      { time: "10:10", rate: 0.03 },
      { time: "10:20", rate: 0.03 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 180 },
      { time: "09:40", reqs: 185 },
      { time: "09:50", reqs: 195 },
      { time: "10:00", reqs: 200 },
      { time: "10:10", reqs: 190 },
      { time: "10:20", reqs: 190 },
    ],
    metricsBreakdown: {
      p50: 42,
      p95: 62,
      p99: 110,
      errorRate: 0.03,
      successRate: 99.97,
      requestVolume: "190 req/min",
      timeoutRate: 0.005,
    },
    endpoints: [
      { method: "POST", path: "https://api.camsonline.com/cas/v3/statement", status: "Healthy", p95: 62, errorRate: "0.03%", reqsPerMin: "190/min" },
    ],
    dependentServices: [
      { name: "Portfolio Valuation Sync", status: "Healthy", p95: 48, errorRate: "0.01%", lastCheck: "5m ago", product: "Investor Sahayogi" },
    ],
    workspaces: [
      { name: "Zenith Financial", wsId: "WS-66291", product: "Investor Sahayogi", status: "Healthy", txVolume: "180 sync/hr", lastActive: "Just now" },
    ],
    recentIssues: [],
    configuration: {
      provider: "CAMS / KFintech",
      environment: "Production",
      region: "India (Chennai)",
      primaryEndpoint: "https://api.camsonline.com/cas/v3",
      backupEndpoint: "https://kfintech.api.com/mf/v1",
      maskedCredential: "cams_rt_••••••12",
      credentialStatus: "Valid (Expires in 175 days)",
      lastValidation: "28 Sep 2026, 05:30",
      tlsCipher: "TLS_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/cams",
      maskedWebhookSecret: "whsec_••••••••1288",
    },
    auditTrail: [
      { time: "05:30", actor: "System", action: "HEALTH_CHECK", result: "Success", reason: "CAS feed ingestion verified", reference: "CHK-12882" },
    ],
    diagnosticChecks: [
      { name: "CAMS Registrar Bridge", status: "pass", latency: "20 ms", detail: "HTTP 200 OK from CAMS Chennai" },
    ],
  },
  {
    id: "setu-aa",
    name: "Setu Account Aggregator",
    category: "Financial Rails",
    provider: "Setu AA / RBI NBFC",
    providerShort: "Setu AA",
    providerLogoType: "setu",
    sahProduct: "Investor Sahayogi",
    sahService: "Bank Statement AA Service",
    status: "Healthy",
    sla: "99.96%",
    slaTarget: 99.90,
    currentUptime: 99.98,
    p95: 38,
    p95Unit: "ms",
    p95Change: "↓ 12%",
    p95TrendDirection: "down",
    errorRate: "0.01%",
    errorRateChange: "↓ 50%",
    errorRateTrendDirection: "down",
    volume: "450 req/min",
    volumeChange: "↑ 30%",
    volumeTrendDirection: "up",
    description: "RBI-regulated Account Aggregator rail for financial information user consent and encrypted statement fetch.",
    environment: "Production",
    primaryEndpoint: "https://aa.setu.co/v1",
    backupEndpoint: "https://dr-aa.setu.co/v1",
    webhookCallback: "Enabled",
    region: "India (Mumbai)",
    version: "v1.8.0",
    workspacesCount: 165,
    sparkline: [42, 40, 39, 37, 38, 39, 38, 37, 38, 38],
    latencySeries: [
      { time: "09:30", p95: 41 },
      { time: "09:40", p95: 39 },
      { time: "09:50", p95: 38 },
      { time: "10:00", p95: 37 },
      { time: "10:10", p95: 38 },
      { time: "10:20", p95: 38 },
    ],
    errorSeries: [
      { time: "09:30", rate: 0.02 },
      { time: "09:40", rate: 0.01 },
      { time: "09:50", rate: 0.01 },
      { time: "10:00", rate: 0.01 },
      { time: "10:10", rate: 0.01 },
      { time: "10:20", rate: 0.01 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 410 },
      { time: "09:40", reqs: 430 },
      { time: "09:50", reqs: 450 },
      { time: "10:00", reqs: 480 },
      { time: "10:10", reqs: 450 },
      { time: "10:20", reqs: 450 },
    ],
    metricsBreakdown: {
      p50: 24,
      p95: 38,
      p99: 72,
      errorRate: 0.01,
      successRate: 99.99,
      requestVolume: "450 req/min",
      timeoutRate: 0.002,
    },
    endpoints: [
      { method: "POST", path: "https://aa.setu.co/v1/consent", status: "Healthy", p95: 38, errorRate: "0.01%", reqsPerMin: "280/min" },
      { method: "POST", path: "https://aa.setu.co/v1/fi/fetch", status: "Healthy", p95: 42, errorRate: "0.01%", reqsPerMin: "170/min" },
    ],
    dependentServices: [
      { name: "AA Consent Management System", status: "Healthy", p95: 28, errorRate: "0.01%", lastCheck: "30s ago", product: "Investor Sahayogi" },
      { name: "Bank Statement Parser", status: "Healthy", p95: 34, errorRate: "0.00%", lastCheck: "1m ago", product: "Investor Sahayogi" },
    ],
    workspaces: [
      { name: "Zenith Financial", wsId: "WS-66291", product: "Investor Sahayogi", status: "Healthy", txVolume: "340 aa/hr", lastActive: "Just now" },
    ],
    recentIssues: [],
    configuration: {
      provider: "Setu AA / RBI NBFC",
      environment: "Production",
      region: "India (Mumbai)",
      primaryEndpoint: "https://aa.setu.co/v1",
      backupEndpoint: "https://dr-aa.setu.co/v1",
      maskedCredential: "aa_live_••••••77",
      credentialStatus: "Valid (RBI FIP/FIU License Active)",
      lastValidation: "28 Sep 2026, 10:30",
      tlsCipher: "TLS_AES_256_GCM_SHA384",
      webhookEndpoint: "https://api.setu.co/v1/callbacks/aa",
      maskedWebhookSecret: "whsec_••••••••7721",
    },
    auditTrail: [
      { time: "10:30", actor: "System", action: "LICENSE_HEARTBEAT", result: "Success", reason: "RBI FIP certificate operational", reference: "RBI-99104" },
    ],
    diagnosticChecks: [
      { name: "Setu AA Gateway", status: "pass", latency: "8 ms", detail: "Mutual TLS connection verified" },
    ],
  },
  {
    id: "income-tax",
    name: "Income Tax e-Filing Portal",
    category: "Tax Government API",
    provider: "Income Tax Dept / CPC",
    providerShort: "Income Tax",
    providerLogoType: "incometax",
    sahProduct: "Tax Sahayogi",
    sahService: "ITR Filing Bridge",
    status: "Down",
    sla: "94.10%",
    slaTarget: 99.50,
    currentUptime: 94.10,
    p95: 2400,
    p95Unit: "ms",
    p95Change: "↑ 380%",
    p95TrendDirection: "up",
    errorRate: "16.4%",
    errorRateChange: "↑ 420%",
    errorRateTrendDirection: "up",
    volume: "50 req/min",
    volumeChange: "↓ 65%",
    volumeTrendDirection: "down",
    description: "Government e-Filing portal for ITR submission, 26AS reconciliation, and annual information statement fetch.",
    environment: "Production",
    primaryEndpoint: "https://eportal.incometax.gov.in/iec/foservices",
    backupEndpoint: "https://dr-eportal.incometax.gov.in",
    webhookCallback: "Disabled",
    region: "India (Bengaluru)",
    version: "v2.0",
    workspacesCount: 92,
    sparkline: [620, 940, 1400, 1800, 2200, 2600, 2400, 2500, 2400, 2400],
    latencySeries: [
      { time: "09:30", p95: 850 },
      { time: "09:40", p95: 1400 },
      { time: "09:50", p95: 1950 },
      { time: "10:00", p95: 2600 },
      { time: "10:10", p95: 2450 },
      { time: "10:20", p95: 2400 },
    ],
    errorSeries: [
      { time: "09:30", rate: 3.2 },
      { time: "09:40", rate: 7.8 },
      { time: "09:50", rate: 12.4 },
      { time: "10:00", rate: 18.2 },
      { time: "10:10", rate: 17.0 },
      { time: "10:20", rate: 16.4 },
    ],
    volumeSeries: [
      { time: "09:30", reqs: 140 },
      { time: "09:40", reqs: 95 },
      { time: "09:50", reqs: 70 },
      { time: "10:00", reqs: 45 },
      { time: "10:10", reqs: 50 },
      { time: "10:20", reqs: 50 },
    ],
    metricsBreakdown: {
      p50: 1200,
      p95: 2400,
      p99: 4800,
      errorRate: 16.4,
      successRate: 83.6,
      requestVolume: "50 req/min",
      timeoutRate: 8.5,
    },
    endpoints: [
      { method: "POST", path: "https://eportal.incometax.gov.in/iec/foservices/itr/submit", status: "Down", p95: 2400, errorRate: "16.4%", reqsPerMin: "50/min" },
    ],
    dependentServices: [
      { name: "ITR Electronic Verification Service", status: "Down", p95: 2400, errorRate: "16.4%", lastCheck: "5s ago", product: "Tax Sahayogi" },
    ],
    workspaces: [
      { name: "TaxPro Consultants", wsId: "WS-54120", product: "Tax Sahayogi", status: "Down", txVolume: "12 itr/hr", lastActive: "15 mins ago" },
    ],
    recentIssues: [
      { date: "28 Sep 2026, 09:25", issue: "CPC Bengaluru gateway 502 Bad Gateway during quarterly filing peak", severity: "Critical", status: "Investigating", affectedWorkspaces: 92 },
    ],
    configuration: {
      provider: "Income Tax Dept / CPC",
      environment: "Production",
      region: "India (Bengaluru)",
      primaryEndpoint: "https://eportal.incometax.gov.in/iec/foservices",
      backupEndpoint: "https://dr-eportal.incometax.gov.in",
      maskedCredential: "itd_eri_••••••88",
      credentialStatus: "Down (Upstream endpoint unresponsive)",
      lastValidation: "28 Sep 2026, 10:22",
      tlsCipher: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      webhookEndpoint: "Disabled",
      maskedWebhookSecret: "—",
    },
    auditTrail: [
      { time: "10:22", actor: "System", action: "UPSTREAM_UNAVAILABLE", result: "Failed", reason: "502 Bad Gateway from CPC load balancer", reference: "INC-99120" },
    ],
    diagnosticChecks: [
      { name: "CPC Gateway Reachability", status: "fail", latency: "2,400 ms", detail: "HTTP 502 Bad Gateway received from upstream" },
    ],
  },
];
